### PR TITLE
Remove my openrndr-template entry

### PR DESCRIPTION
**Pull request by ricardomatias**
I don't really use it anymore.

### CODE REVIEW

**Comment by hamoid** [comment]
Thanks! :) ps. you can mark it as archived in github (if that's the state).

**Comment by ricardomatias** [comment]
Cheers, it's indeed better to mark it as archived.

**Comment by hamoid** [comment]
I wonder if instead of deleting it I should move to an archived zone. Because if I try to find repos again in a few weeks, how to avoid re-adding it?

**Comment by hamoid** [comment]
To be clear, there's an archive option in github, and then there are archived sublists in this readme :)

**Pull request merged**
